// contst of actions and reducers  
export const IS_USER_OPEN = 'APP_ACTION/IS_USER_OPEN';
export const CHANGE_PAGE_NAME = 'APP_ACTION/CHANGE_PAGE_NAME';
export const OPEN_USER_INFO = 'USER_INFO_ACTION/OPEN_USER_INFO';
export const CONTACT_USER_SUBMIT = 'CONTACT_ACTION/CONTACT_USER_SUBMIT';
export const USER_LOGIN = 'USER_LOGIN_ACTION/USER_LOGIN';
export const CLEAR_USER_FORM_ACTION = 'USER_LOGIN_ACTION/CLEAR_USER_FORM_ACTION';